# Project — node 1.20.1 (forge)
project.version=0.1.0+1.20.1
project.java=17
project.build-java=21
project.minecraft=1.20.1
project.enabled-loaders=forge

# Version Ranges
mod.minecraft-range=[1.20.1, 1.21)
mod.forge-loader-range=[47,)

# Mixin 兼容等级 (multiloader 插件必需属性, 与 LMA 同款取值)
mixin.compat.common=JAVA_17
mixin.compat.fabric=JAVA_17
mixin.compat.forge=JAVA_17
mixin.compat.neoforge=JAVA_17
