# Project — node 1.21.1 (neoforge)
project.version=0.1.0+1.21.1
project.java=21
project.build-java=21
project.minecraft=1.21.1
project.enabled-loaders=neoforge

# Version Ranges
mod.minecraft-range=[1.21.1, 1.22)
mod.neoforge-loader-range=[1,)

# Mixin 兼容等级 (multiloader 插件必需属性, 与 LMA 同款取值)
mixin.compat.common=JAVA_21
mixin.compat.fabric=JAVA_21
mixin.compat.forge=JAVA_21
mixin.compat.neoforge=JAVA_21
